export const appointments = [
  {
    id: 1,
    name: 'Priya Sharma',
    email: 'priya.sharma@gmail.com',
    sessionType: 'Free Call Session',
    date: 'May 23, 2024',
    time: '10:00 AM',
    status: 'Confirmed',
  },
  {
    id: 2,
    name: 'Rahul Verma',
    email: 'rahul.verma@gmail.com',
    sessionType: 'Paid 1 Hour Call Session',
    date: 'May 23, 2024',
    time: '11:30 AM',
    status: 'Confirmed',
  },
  {
    id: 3,
    name: 'Ananya Patel',
    email: 'ananya.patel@gmail.com',
    sessionType: 'Handwriting Session',
    date: 'May 23, 2024',
    time: '01:00 PM',
    status: 'Pending',
  },
  {
    id: 4,
    name: 'Vikram Singh',
    email: 'vikram.singh@gmail.com',
    sessionType: 'Life Coaching Session',
    date: 'May 23, 2024',
    time: '03:00 PM',
    status: 'Confirmed',
  },
  {
    id: 5,
    name: 'Sneha Iyer',
    email: 'sneha.iyer@gmail.com',
    sessionType: 'Paid 1 Hour Call Session',
    date: 'May 24, 2024',
    time: '10:00 AM',
    status: 'Confirmed',
  },
  {
    id: 6,
    name: 'Karan Mehta',
    email: 'karan.mehta@gmail.com',
    sessionType: 'Free Call Session',
    date: 'May 24, 2024',
    time: '11:00 AM',
    status: 'Cancelled',
  },
  {
    id: 7,
    name: 'Meera Nair',
    email: 'meera.nair@gmail.com',
    sessionType: 'Handwriting Session',
    date: 'May 24, 2024',
    time: '02:00 PM',
    status: 'Confirmed',
  },
  {
    id: 8,
    name: 'Arjun Reddy',
    email: 'arjun.reddy@gmail.com',
    sessionType: 'Life Coaching Session',
    date: 'May 24, 2024',
    time: '04:30 PM',
    status: 'Pending',
  },
  {
    id: 9,
    name: 'Divya Tiwari',
    email: 'divya.tiwari@gmail.com',
    sessionType: 'Paid 1 Hour Call Session',
    date: 'May 25, 2024',
    time: '10:30 AM',
    status: 'Confirmed',
  },
  {
    id: 10,
    name: 'Rohit Kapoor',
    email: 'rohit.kapoor@gmail.com',
    sessionType: 'Handwriting Session',
    date: 'May 25, 2024',
    time: '01:30 PM',
    status: 'Confirmed',
  },
]

export const stats = [
  { id: 1, icon: 'Calendar', number: 128, title: 'Total Appointments', subtitle: 'All Time' },
  { id: 2, icon: 'Phone', number: 42, title: 'Free Call Sessions', subtitle: 'All Time' },
  { id: 3, icon: 'Clock', number: 38, title: 'Paid 1 Hour Sessions', subtitle: 'All Time' },
  { id: 4, icon: 'Pen', number: 26, title: 'Handwriting Sessions', subtitle: 'All Time' },
  { id: 5, icon: 'User', number: 22, title: 'Life Coaching Sessions', subtitle: 'All Time' },
]

export const sessionTypes = [
  'All Types',
  'Free Call Session',
  'Paid 1 Hour Call Session',
  'Handwriting Session',
  'Life Coaching Session',
]

export const statusOptions = ['All Status', 'Confirmed', 'Pending', 'Cancelled']
